language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ParsaSharifi97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ParsaSharifi97/docker-react npm run test -- --coverage